# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" ];
  boot.supportedFilesystems = [ "zfs" "ext4" "vfat" "ntfs" "btrfs"];
  boot.extraModulePackages = [ ];
  boot.zfs.extraPools = [ "zpool" ];
  services.zfs = {
    autoScrub.enable = true;
    autoSnapshot.enable = true;
  };

  # Clean root on Every boot. Erase your darlings
   boot.initrd.postDeviceCommands = lib.mkAfter ''
     zfs rollback -r zpool/root@blank
   '';
  # Multi-partition disk scheduler to none
  boot.kernelParams = [ "elevator=none" "nvidia.NVreg_EnableGpuFirmware=0" "usbcore.autosuspend=-1" ];

  fileSystems."/" =
    { device = "zpool/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "zpool/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fd44011a-9459-48b5-a1cd-f2acf9c7f85c";
      fsType = "ext4";
    };

  fileSystems."/persist" =
    { device = "zpool/persist";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FDE8-41C1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/sGames" =
    { device = "/dev/disk/by-uuid/1573eb3f-db14-49c8-ad91-6cb055c76865";
      fsType = "btrfs";
      options = [ "rw" "nofail" "defaults" ];
    };

  fileSystems."/mnt/sharedGames" = {
    device = "/dev/disk/by-uuid/8413daac-493c-4872-9ea0-2377465982a3";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/nixGames" = {
    device = "/dev/disk/by-uuid/f9996c00-95d5-4d20-af04-0e38a14fe12b";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults"  ];
  };

  fileSystems."/mnt/archGames" = {
    device = "/dev/disk/by-uuid/e9a90d6c-4edf-4f90-8bdb-e556fec1f6ed";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/C" =
    { device = "/dev/disk/by-uuid/1CA2D086A2D065B4";
      fsType = "ntfs-3g";
      options = [ "nofail"];
    };

  fileSystems."/mnt/games2" =
    { device = "/dev/disk/by-uuid/54BE5F16BE5EEFCA";
      fsType = "ntfs-3g";
      options = [ "nofail"];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
