# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, inputs, lib, pkgs, modulesPath, ... }:

let
  pkgs-unstable = inputs.hyprland.inputs.nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system};
  ntfsDrives = [
    { name = "C";      uuid = "1CA2D086A2D065B4"; mountPoint = "/mnt/C"; }
    { name = "games2"; uuid = "54BE5F16BE5EEFCA"; mountPoint = "/mnt/games2"; }
  ];
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" "i915" ];
  boot.supportedFilesystems = [ "zfs" "ext4" "vfat" "ntfs" "btrfs" ];
  boot.extraModulePackages = [ ];
  boot.zfs.extraPools = [ "zpool" ];
  services.zfs = {
    autoScrub.enable = true;
    autoSnapshot.enable = true;
  };

  # Give USB hub chains time to enumerate before ZFS decrypt prompt
  boot.initrd.systemd.services.usb-settle = {
    description = "Wait for USB hub chains to enumerate";
    wantedBy = [ "sysinit.target" ];
    before = [ "systemd-cryptsetup@.service" "zfs-import.target" ];
    after = [ "systemd-udevd.service" ];
    unitConfig.DefaultDependencies = false;
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "/bin/sleep 3";
    };
  };

  # Clean root on every boot. Erase your darlings
  boot.initrd.systemd.services.rollback-root = {
    description = "Rollback ZFS root to blank snapshot";
    wantedBy = [ "initrd.target" ];
    after = [ "zfs-import.target" ];
    before = [ "sysroot.mount" ];
    unitConfig.DefaultDependencies = false;
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${config.boot.zfs.package}/sbin/zfs rollback -r zpool/root@blank";
    };
  };
  # Multi-partition disk scheduler to none
  boot.kernelParams = [
    "elevator=none"
    "nvidia.NVreg_EnableGpuFirmware=0"
    "usbcore.autosuspend=-1"
    "iommu=pt"
    # Force i915 for iGPU so it registers the audio component needed by snd_hda_intel for SPDIF
    "xe.force_probe=!a780"
    "i915.force_probe=a780"
    # Skip HID init report fetches that cause ~5s timeout per interface on KVM switch
    # GMMK Pro ANSI (320f:5044) and Logitech USB Receiver (046d:c547)
    "usbhid.quirks=0x320F:0x5044:0x20000000,0x046D:0xC547:0x20000000"
  ];

  fileSystems."/" = {
    device = "zpool/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zpool/nix";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fd44011a-9459-48b5-a1cd-f2acf9c7f85c";
    fsType = "ext4";
  };

  fileSystems."/persist" = {
    device = "zpool/persist";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FDE8-41C1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/sGames" = {
    device = "/dev/disk/by-uuid/1573eb3f-db14-49c8-ad91-6cb055c76865";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/sharedGames" = {
    device = "/dev/disk/by-uuid/8413daac-493c-4872-9ea0-2377465982a3";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/nixGames" = {
    device = "/dev/disk/by-uuid/f9996c00-95d5-4d20-af04-0e38a14fe12b";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/archGames" = {
    device = "/dev/disk/by-uuid/e9a90d6c-4edf-4f90-8bdb-e556fec1f6ed";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/C" = {
    device = "/dev/disk/by-uuid/1CA2D086A2D065B4";
    fsType = "ntfs-3g";
    options = [ "nofail" "noauto" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/games2" = {
    device = "/dev/disk/by-uuid/54BE5F16BE5EEFCA";
    fsType = "ntfs-3g";
    options = [ "nofail" "noauto" "x-systemd.device-timeout=1" ];
  };

  systemd.services = lib.listToAttrs (map (drive: {
    name = "ntfs-mount-${drive.name}";
    value = {
      description = "Mount ${drive.mountPoint} NTFS (ntfsfix on dirty)";
      wantedBy = [ "multi-user.target" ];
      after = [ "dev-disk-by\\x2duuid-${drive.uuid}.device" ];
      wants = [ "dev-disk-by\\x2duuid-${drive.uuid}.device" ];
      unitConfig.ConditionPathExists = "/dev/disk/by-uuid/${drive.uuid}";
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "ntfs-mount-${drive.name}" ''
          if ! ${pkgs.util-linux}/bin/mount ${drive.mountPoint} 2>/dev/null; then
            ${pkgs.ntfs3g}/bin/ntfsfix -d /dev/disk/by-uuid/${drive.uuid}
            ${pkgs.util-linux}/bin/mount ${drive.mountPoint}
          fi
        '';
      };
    };
  }) ntfsDrives);

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    i2c.enable = true;
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      package = pkgs-unstable.mesa;
      package32 = pkgs-unstable.pkgsi686Linux.mesa;
      enable = true;
      enable32Bit = true;
    };
  };
}
