# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, inputs, lib, pkgs, modulesPath, ... }:

let
  pkgs-unstable = inputs.hyprland.inputs.nixpkgs.legacyPackages.${pkgs.stdenv.hostPlatform.system};
  ntfsDrives = [
    { name = "C";      uuid = "1CA2D086A2D065B4"; mountPoint = "/mnt/C"; }
    { name = "games2"; uuid = "54BE5F16BE5EEFCA"; mountPoint = "/mnt/games2"; }
  ];
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" ];
  boot.supportedFilesystems = [ "zfs" "ext4" "vfat" "ntfs" "btrfs" ];
  boot.extraModulePackages = [ ];
  boot.zfs.extraPools = [ "zpool" ];
  services.zfs = {
    autoScrub.enable = true;
    autoSnapshot.enable = true;
  };

  # Give USB hub chains time to enumerate before ZFS decrypt prompt
  boot.initrd.preDeviceCommands = "sleep 3";

  # Clean root on Every boot. Erase your darlings
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r zpool/root@blank
  '';
  # Multi-partition disk scheduler to none
  boot.kernelParams = [
    "elevator=none"
    "nvidia.NVreg_EnableGpuFirmware=0"
    "usbcore.autosuspend=-1"
    "iommu=pt"
  ];

  fileSystems."/" = {
    device = "zpool/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "zpool/nix";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fd44011a-9459-48b5-a1cd-f2acf9c7f85c";
    fsType = "ext4";
  };

  fileSystems."/persist" = {
    device = "zpool/persist";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FDE8-41C1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/mnt/sGames" = {
    device = "/dev/disk/by-uuid/1573eb3f-db14-49c8-ad91-6cb055c76865";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/sharedGames" = {
    device = "/dev/disk/by-uuid/8413daac-493c-4872-9ea0-2377465982a3";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/nixGames" = {
    device = "/dev/disk/by-uuid/f9996c00-95d5-4d20-af04-0e38a14fe12b";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/archGames" = {
    device = "/dev/disk/by-uuid/e9a90d6c-4edf-4f90-8bdb-e556fec1f6ed";
    fsType = "btrfs";
    options = [ "rw" "nofail" "defaults" ];
  };

  fileSystems."/mnt/C" = {
    device = "/dev/disk/by-uuid/1CA2D086A2D065B4";
    fsType = "ntfs-3g";
    options = [ "nofail" "noauto" "x-systemd.device-timeout=1" ];
  };

  fileSystems."/mnt/games2" = {
    device = "/dev/disk/by-uuid/54BE5F16BE5EEFCA";
    fsType = "ntfs-3g";
    options = [ "nofail" "noauto" "x-systemd.device-timeout=1" ];
  };

  systemd.services = lib.listToAttrs (map (drive: {
    name = "ntfs-mount-${drive.name}";
    value = {
      description = "Mount ${drive.mountPoint} NTFS (ntfsfix on dirty)";
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStart = pkgs.writeShellScript "ntfs-mount-${drive.name}" ''
          if ! mount ${drive.mountPoint} 2>/dev/null; then
            ${pkgs.ntfs3g}/bin/ntfsfix -d /dev/disk/by-uuid/${drive.uuid}
            mount ${drive.mountPoint}
          fi
        '';
      };
    };
  }) ntfsDrives);

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      package = pkgs-unstable.mesa;
      package32 = pkgs-unstable.pkgsi686Linux.mesa;
      enable = true;
      enable32Bit = true;
    };
  };
}
