# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.supportedFilesystems = [ "zfs" "ext4" "vfat" "ntfs" "btrfs"];
  boot.extraModulePackages = [ ];
  boot.zfs.extraPools = [ "zpool" ];
  services.zfs = {
    autoScrub.enable = true;
    autoSnapshot.enable = true;
  };

  # Clean root on Every boot. Erase your darlings
   boot.initrd.postDeviceCommands = lib.mkAfter ''
     zfs rollback -r zpool/root@blank
   '';
  # Multi-partition disk scheduler to none
  boot.kernelParams = [ "elevator=none" ];

  fileSystems = {
    "/" =
      { device = "zpool/root";
        fsType = "zfs";
      };

    "/nix" =
      { device = "zpool/nix";
        fsType = "zfs";
      };

    "/home" =
      { device = "zpool/home";
        fsType = "zfs";
      };

    "/persist" =
      { device = "zpool/persist";
        fsType = "zfs";
      };

    "/boot" =
      { device = "/dev/disk/by-uuid/6246-7993";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
